# Relatorio de Analise V

## Tratamento de Dados Faltantes

In [16]:
import pandas as pd

In [17]:
dados = pd.read_csv("dados/aluguel_residenciais.csv", sep = ";")

In [18]:
dados.isnull() #ele cria um DataFrame e marca TRUE se o dado for nulo

        Tipo  Bairro  Quartos  Vagas  Suites   Area  Valor  Condominio   IPTU
0      False   False    False  False   False  False  False       False  False
1      False   False    False  False   False  False  False        True   True
2      False   False    False  False   False  False  False       False  False
3      False   False    False  False   False  False  False       False   True
4      False   False    False  False   False  False  False       False  False
5      False   False    False  False   False  False  False        True   True
6      False   False    False  False   False  False  False        True   True
7      False   False    False  False   False  False  False       False  False
8      False   False    False  False   False  False  False       False  False
9      False   False    False  False   False  False  False       False  False
10     False   False    False  False   False  False  False       False   True
11     False   False    False  False   False  False  False       False  False
12     False   False    False  False   False  False  False        True   True
13     False   False    False  False   False  False  False       False  False
14     False   False    False  False   False  False  False       False  False
15     False   False    False  False   False  False  False       False  False
16     False   False    False  False   False  False  False       False   True
17     False   False    False  False   False  False  False       False   True
18     False   False    False  False   False  False  False       False   True
19     False   False    False  False   False  False  False       False  False
20     False   False    False  False   False  False  False       False  False
21     False   False    False  False   False  False  False       False  False
22     False   False    False  False   False  False  False        True   True
23     False   False    False  False   False  False  False       False   True
24     False   False    False  False   False  False  False       False  False
25     False   False    False  False   False  False  False       False  False
26     False   False    False  False   False  False  False       False   True
27     False   False    False  False   False  False  False       False  False
28     False   False    False  False   False  False  False       False  False
29     False   False    False  False   False  False  False       False  False
...      ...     ...      ...    ...     ...    ...    ...         ...    ...
21796  False   False    False  False   False  False  False       False  False
21797  False   False    False  False   False  False  False       False  False
21798  False   False    False  False   False  False  False       False  False
21799  False   False    False  False   False  False  False       False  False
21800  False   False    False  False   False  False  False       False  False
21801  False   False    False  False   False  False  False       False   True
21802  False   False    False  False   False  False  False       False   True
21803  False   False    False  False   False  False  False       False  False
21804  False   False    False  False   False  False  False        True  False
21805  False   False    False  False   False  False  False       False  False
21806  False   False    False  False   False  False  False       False  False
21807  False   False    False  False   False  False  False       False  False
21808  False   False    False  False   False  False  False       False  False
21809  False   False    False  False   False  False  False       False  False
21810  False   False    False  False   False  False  False       False  False
21811  False   False    False  False   False  False  False       False  False
21812  False   False    False  False   False  False  False       False  False
21813  False   False    False  False   False  False  False       False  False
21814  False   False    False  False   False  False  False       False   True
21815  False   False    False  False   False  False  False       False  False
21816  False   False    False  False   False  False  False       False  False
21817  False   False    False  False   False  False  False       False  False
21818  False   False    False  False   False  False  False       False  False
21819  False   False    False  False   False  False  False       False   True
21820  False   False    False  False   False  False  False       False  False
21821  False   False    False  False   False  False  False       False  False
21822  False   False    False  False   False  False  False       False  False
21823  False   False    False  False   False  False  False       False  False
21824  False   False    False  False   False  False  False       False  False
21825  False   False    False  False   False  False  False       False   True

[21826 rows x 9 columns]

In [19]:
dados.notnull() #ele cria um DataFrame e marca FALSE se o dado for nulo

       Tipo  Bairro  Quartos  Vagas  Suites  Area  Valor  Condominio   IPTU
0      True    True     True   True    True  True   True        True   True
1      True    True     True   True    True  True   True       False  False
2      True    True     True   True    True  True   True        True   True
3      True    True     True   True    True  True   True        True  False
4      True    True     True   True    True  True   True        True   True
5      True    True     True   True    True  True   True       False  False
6      True    True     True   True    True  True   True       False  False
7      True    True     True   True    True  True   True        True   True
8      True    True     True   True    True  True   True        True   True
9      True    True     True   True    True  True   True        True   True
10     True    True     True   True    True  True   True        True  False
11     True    True     True   True    True  True   True        True   True
12     True    True     True   True    True  True   True       False  False
13     True    True     True   True    True  True   True        True   True
14     True    True     True   True    True  True   True        True   True
15     True    True     True   True    True  True   True        True   True
16     True    True     True   True    True  True   True        True  False
17     True    True     True   True    True  True   True        True  False
18     True    True     True   True    True  True   True        True  False
19     True    True     True   True    True  True   True        True   True
20     True    True     True   True    True  True   True        True   True
21     True    True     True   True    True  True   True        True   True
22     True    True     True   True    True  True   True       False  False
23     True    True     True   True    True  True   True        True  False
24     True    True     True   True    True  True   True        True   True
25     True    True     True   True    True  True   True        True   True
26     True    True     True   True    True  True   True        True  False
27     True    True     True   True    True  True   True        True   True
28     True    True     True   True    True  True   True        True   True
29     True    True     True   True    True  True   True        True   True
...     ...     ...      ...    ...     ...   ...    ...         ...    ...
21796  True    True     True   True    True  True   True        True   True
21797  True    True     True   True    True  True   True        True   True
21798  True    True     True   True    True  True   True        True   True
21799  True    True     True   True    True  True   True        True   True
21800  True    True     True   True    True  True   True        True   True
21801  True    True     True   True    True  True   True        True  False
21802  True    True     True   True    True  True   True        True  False
21803  True    True     True   True    True  True   True        True   True
21804  True    True     True   True    True  True   True       False   True
21805  True    True     True   True    True  True   True        True   True
21806  True    True     True   True    True  True   True        True   True
21807  True    True     True   True    True  True   True        True   True
21808  True    True     True   True    True  True   True        True   True
21809  True    True     True   True    True  True   True        True   True
21810  True    True     True   True    True  True   True        True   True
21811  True    True     True   True    True  True   True        True   True
21812  True    True     True   True    True  True   True        True   True
21813  True    True     True   True    True  True   True        True   True
21814  True    True     True   True    True  True   True        True  False
21815  True    True     True   True    True  True   True        True   True
21816  True    True     True   True    True  True   True        True   True
21817  True    True     True   True    True  True   True        True   True
21818  True    True     True   True    True  True   True        True   True
21819  True    True     True   True    True  True   True        True  False
21820  True    True     True   True    True  True   True        True   True
21821  True    True     True   True    True  True   True        True   True
21822  True    True     True   True    True  True   True        True   True
21823  True    True     True   True    True  True   True        True   True
21824  True    True     True   True    True  True   True        True   True
21825  True    True     True   True    True  True   True        True  False

[21826 rows x 9 columns]

In [20]:
dados.info() #usado para analizar quais colunas tem valores NULOS!!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21826 entries, 0 to 21825
Data columns (total 9 columns):
Tipo          21826 non-null object
Bairro        21826 non-null object
Quartos       21826 non-null int64
Vagas         21826 non-null int64
Suites        21826 non-null int64
Area          21826 non-null int64
Valor         21826 non-null float64
Condominio    20758 non-null float64
IPTU          15685 non-null float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.5+ MB

In [21]:
dados[dados["Valor"].isnull()] #ele pega todos os valores nulos da coluna "Valor"

Empty DataFrame
Columns: [Tipo, Bairro, Quartos, Vagas, Suites, Area, Valor, Condominio, IPTU]
Index: []

In [22]:
dados[dados["IPTU"].isnull()] #ele pega todos os valores nulos da coluna "IPTU"

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
6,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
10,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,NaN
12,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
16,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,NaN
17,Apartamento,Olaria,3,1,0,68,1000.0,670.0,NaN
18,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN
22,Casa,Campo Grande,4,1,2,400,12000.0,NaN,NaN
23,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,NaN
26,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,NaN
33,Apartamento,Recreio dos Bandeirantes,2,2,2,90,3000.0,1340.0,NaN
34,Apartamento,Recreio dos Bandeirantes,3,2,2,100,2600.0,380.0,NaN
42,Casa de Condomínio,Barra da Tijuca,5,10,5,1600,25000.0,1600.0,NaN
52,Apartamento,Ipanema,3,2,1,150,8000.0,2400.0,NaN
54,Casa,Méier,2,0,0,51,1500.0,50.0,NaN
55,Apartamento,Jardim Botânico,2,2,0,95,4000.0,1170.0,NaN
58,Casa de Condomínio,Freguesia (Jacarepaguá),5,3,1,140,2500.0,1200.0,NaN
67,Apartamento,Bonsucesso,2,1,0,77,1500.0,740.0,NaN
70,Apartamento,Laranjeiras,2,1,0,54,2300.0,582.0,NaN
71,Quitinete,Centro,0,0,0,30,800.0,505.0,NaN
72,Apartamento,Jacarepaguá,2,1,1,69,2000.0,780.0,NaN
81,Casa de Vila,Piedade,2,1,0,70,1300.0,NaN,NaN
85,Apartamento,Olaria,2,1,0,53,1100.0,160.0,NaN
86,Quitinete,Copacabana,1,0,0,29,1200.0,460.0,NaN
89,Apartamento,Lagoa,3,1,2,250,13900.0,2500.0,NaN
96,Casa,Maracanã,8,3,5,259,7000.0,NaN,NaN
98,Apartamento,Catete,2,0,0,75,3350.0,455.0,NaN
100,Casa,Benfica,1,0,0,33,1200.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
21723,Apartamento,Jacarepaguá,3,1,1,63,1500.0,700.0,NaN
21725,Apartamento,Méier,3,0,0,79,1600.0,270.0,NaN
21728,Quitinete,Flamengo,1,0,0,23,900.0,605.0,NaN
21733,Apartamento,Parada de Lucas,2,1,0,55,900.0,140.0,NaN
21735,Apartamento,Barra da Tijuca,2,1,1,67,1600.0,750.0,NaN
21736,Apartamento,Copacabana,3,0,1,110,3000.0,900.0,NaN
21738,Apartamento,Campo Grande,2,1,1,90,1600.0,600.0,NaN
21742,Apartamento,Recreio dos Bandeirantes,1,1,1,79,1900.0,479.0,NaN
21747,Apartamento,Curicica,2,1,0,50,800.0,410.0,NaN
21748,Quitinete,Centro,1,0,0,24,1100.0,323.0,NaN
21749,Apartamento,Méier,2,1,0,64,1100.0,644.0,NaN
21751,Apartamento,Cascadura,2,1,1,56,1200.0,568.0,NaN
21756,Casa,Campo Grande,1,0,0,50,600.0,NaN,NaN
21759,Apartamento,Irajá,2,1,0,62,1000.0,300.0,NaN
21762,Casa de Vila,Pavuna,2,0,0,55,600.0,NaN,NaN
21765,Apartamento,Campo Grande,2,1,0,45,770.0,230.0,NaN
21769,Apartamento,Barra da Tijuca,4,3,4,366,12800.0,3157.0,NaN
21772,Apartamento,Recreio dos Bandeirantes,4,2,2,230,7000.0,1490.0,NaN
21775,Apartamento,Taquara,2,1,1,71,1300.0,470.0,NaN
21776,Apartamento,Irajá,2,1,0,50,900.0,300.0,NaN
21781,Casa,Recreio dos Bandeirantes,4,2,2,352,6500.0,NaN,NaN
21784,Apartamento,Recreio dos Bandeirantes,3,2,1,113,2100.0,611.0,NaN
21789,Apartamento,Olaria,2,0,0,67,1250.0,150.0,NaN
21793,Casa,Bento Ribeiro,2,1,0,60,1400.0,NaN,NaN
21794,Apartamento,Flamengo,1,0,0,48,2200.0,478.0,NaN
21801,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,NaN
21802,Apartamento,Campinho,2,0,0,63,800.0,392.0,NaN
21814,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,NaN
21819,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
21825,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN

In [23]:
dados[dados["Condominio"].isnull()] #ele pega todos os valores nulos da coluna "Condominio"

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
5,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
6,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
12,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
22,Casa,Campo Grande,4,1,2,400,12000.0,NaN,NaN
81,Casa de Vila,Piedade,2,1,0,70,1300.0,NaN,NaN
96,Casa,Maracanã,8,3,5,259,7000.0,NaN,NaN
100,Casa,Benfica,1,0,0,33,1200.0,NaN,NaN
144,Casa,Jardim Carioca,3,2,1,135,3000.0,NaN,NaN
160,Casa,Lins de Vasconcelos,2,0,0,40,950.0,NaN,50.0
220,Casa de Vila,Oswaldo Cruz,1,0,1,40,800.0,NaN,NaN
238,Casa,Grajaú,5,4,2,450,7000.0,NaN,500.0
253,Casa,Campo Grande,3,0,0,200,2100.0,NaN,NaN
264,Casa,Bonsucesso,2,0,0,51,1000.0,NaN,NaN
286,Casa,Engenho Novo,2,0,0,70,1100.0,NaN,NaN
303,Casa de Vila,Quintino Bocaiúva,2,1,0,48,750.0,NaN,NaN
310,Casa,Jardim Botânico,2,4,1,107,9500.0,NaN,1091.0
316,Casa,Recreio dos Bandeirantes,4,4,2,367,12000.0,NaN,653.0
334,Casa,Botafogo,12,5,0,500,18000.0,NaN,1800.0
339,Casa,Catete,10,0,10,300,15000.0,NaN,220.0
355,Quitinete,Gardênia Azul,1,0,0,20,485.0,NaN,NaN
357,Casa,São Conrado,4,0,4,1200,25000.0,NaN,NaN
378,Casa,Campo Grande,2,1,2,100,1500.0,NaN,30.0
399,Casa,Santa Teresa,5,3,0,260,7000.0,NaN,163.0
424,Casa,Vila da Penha,1,0,0,40,850.0,NaN,NaN
427,Quitinete,Centro,1,0,1,15,750.0,NaN,NaN
434,Casa,Vaz Lobo,1,0,0,35,400.0,NaN,NaN
481,Casa,Campo Grande,2,1,0,100,1300.0,NaN,NaN
542,Casa,Campo Grande,2,0,0,70,1000.0,NaN,NaN
567,Casa,Ramos,2,0,0,40,950.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
21289,Casa de Condomínio,São Cristóvão,2,0,2,120,2000.0,NaN,NaN
21292,Casa,Jacaré,2,1,0,80,1500.0,NaN,150.0
21304,Casa,Campo Grande,1,1,0,61,830.0,NaN,NaN
21325,Casa de Vila,Olaria,1,0,0,40,800.0,NaN,NaN
21331,Casa,Curicica,3,5,1,150,2500.0,NaN,1200.0
21353,Casa de Vila,Tijuca,2,0,0,75,2200.0,NaN,NaN
21366,Casa de Vila,Riachuelo,2,0,0,43,1000.0,NaN,120.0
21367,Casa,Inhoaíba,1,0,0,50,600.0,NaN,NaN
21389,Casa,Pechincha,5,3,1,300,3000.0,NaN,290.0
21401,Casa,Méier,4,1,0,180,2500.0,NaN,80.0
21446,Casa,Irajá,2,1,1,60,1150.0,NaN,NaN
21448,Casa,Jardim Botânico,7,6,4,845,35000.0,NaN,NaN
21454,Casa,Turiaçu,2,1,0,45,700.0,NaN,NaN
21542,Casa,Campo Grande,2,0,0,116,1100.0,NaN,NaN
21545,Casa,Centro,2,0,0,207,4000.0,NaN,NaN
21555,Casa,Campo Grande,3,0,1,140,1500.0,NaN,NaN
21562,Casa,Taquara,3,3,0,280,4000.0,NaN,1200.0
21579,Casa,Rocha Miranda,1,0,0,44,700.0,NaN,NaN
21582,Casa,Andaraí,3,1,0,75,2950.0,NaN,NaN
21588,Casa de Vila,Quintino Bocaiúva,2,0,0,58,1000.0,NaN,NaN
21614,Casa,Engenho Novo,1,0,0,40,450.0,NaN,NaN
21667,Casa,Maracanã,4,2,1,240,6500.0,NaN,700.0
21672,Casa,Campo Grande,2,1,2,86,1500.0,NaN,NaN
21699,Casa,Vila da Penha,2,1,0,80,1500.0,NaN,NaN
21716,Casa de Vila,Riachuelo,3,0,0,73,850.0,NaN,NaN
21756,Casa,Campo Grande,1,0,0,50,600.0,NaN,NaN
21762,Casa de Vila,Pavuna,2,0,0,55,600.0,NaN,NaN
21781,Casa,Recreio dos Bandeirantes,4,2,2,352,6500.0,NaN,NaN
21793,Casa,Bento Ribeiro,2,1,0,60,1400.0,NaN,NaN
21804,Casa,Centro,5,0,1,160,5000.0,NaN,80.0

In [24]:
#Nos sabemos pelo dados.info() que existem 9 valores na coluna "Valor" que sao NaN
#
#para retirar esses 9 valores utilizamos o dropna() e informamos a coluna que gostaria de eliminar os valores NaN

A = dados.shape[0] #mostrando a quantidade de registros antes do DROPNA()

dados.dropna(subset = ["Valor"], inplace = True) #fazendo o drop

B = dados.shape[0]

A - B #Mostrando a diferenca entre antes e depois do DROPNA() na coluna VALOR

0

In [25]:
selecao = (dados["Tipo"] == "Apartamento") & (dados["Condominio"].isnull())

In [26]:
A = dados.shape[0] 

dados = dados[~selecao] #o TIO INVERTE A SELECAO (WOOOOW)

B = dados.shape[0]

A - B

0

In [32]:
dados_2 = dados.fillna({"Condominio": 0, "IPTU": 0}) #o FILLNA() substitui todos os valores NaN pelo valor que quiser!!

In [33]:
dados_2

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0
4,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
5,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0
6,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0
7,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0
8,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0
9,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0
10,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,0.0
11,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0
12,Casa de Condomínio,Taquara,3,1,1,115,2000.0,0.0,0.0
13,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0
14,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0
15,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0
16,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,0.0
17,Apartamento,Olaria,3,1,0,68,1000.0,670.0,0.0
18,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,0.0
19,Apartamento,Ipanema,3,1,1,125,7000.0,2100.0,463.0
20,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0
21,Apartamento,Barra da Tijuca,3,3,1,175,4200.0,1500.0,500.0
22,Casa,Campo Grande,4,1,2,400,12000.0,0.0,0.0
23,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,0.0
24,Apartamento,Copacabana,3,1,2,378,10000.0,2150.0,700.0
25,Apartamento,Copacabana,3,0,0,180,5500.0,1780.0,420.0
26,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,0.0
27,Apartamento,Leblon,3,1,0,110,3900.0,1500.0,120.0
28,Quitinete,Copacabana,1,0,0,27,1300.0,380.0,53.0
29,Apartamento,Jardim Oceânico,3,3,1,200,3500.0,1780.0,496.0
...,...,...,...,...,...,...,...,...,...
21796,Apartamento,Ipanema,1,0,0,55,2000.0,630.0,19.0
21797,Apartamento,Recreio dos Bandeirantes,3,2,1,100,2500.0,650.0,1864.0
21798,Apartamento,Jardim Botânico,3,1,2,145,5000.0,1296.0,317.0
21799,Apartamento,Recreio dos Bandeirantes,3,2,1,115,2000.0,482.0,166.0
21800,Apartamento,Barra da Tijuca,1,1,0,62,1700.0,945.0,180.0
21801,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,0.0
21802,Apartamento,Campinho,2,0,0,63,800.0,392.0,0.0
21803,Apartamento,Freguesia (Jacarepaguá),2,1,0,60,500.0,900.0,148.0
21804,Casa,Centro,5,0,1,160,5000.0,0.0,80.0
21805,Apartamento,Todos os Santos,3,0,0,54,1500.0,289.0,35.0
21806,Apartamento,Recreio dos Bandeirantes,2,1,1,105,2100.0,648.0,156.0
21807,Apartamento,Jacarepaguá,2,1,1,78,2200.0,790.0,180.0
21808,Apartamento,Leblon,1,1,1,50,4300.0,1730.0,259.0
21809,Apartamento,Copacabana,2,0,1,70,4100.0,700.0,90.0
21810,Apartamento,Copacabana,1,0,0,50,1950.0,450.0,70.0
21811,Apartamento,Barra da Tijuca,2,1,1,85,2250.0,1561.0,197.0
21812,Apartamento,Barra da Tijuca,3,2,0,98,2300.0,887.0,177.0
21813,Apartamento,Barra da Tijuca,3,2,2,140,5500.0,1900.0,700.0
21814,Apartamento,Recreio dos Bandeirantes,3,2,1,88,1550.0,790.0,0.0
21815,Quitinete,Copacabana,1,0,0,22,1500.0,286.0,200.0
21816,Apartamento,Leblon,3,0,1,80,3000.0,1010.0,249.0
21817,Apartamento,Ipanema,3,1,2,150,15000.0,1400.0,600.0
21818,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
21819,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,0.0
21820,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0
21821,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
21822,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
21823,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
21824,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
21825,Apartamento,Leblon,2,0,0,70,3000.0,760.0,0.0

In [34]:
dados_2.to_csv("dados/alugueis_residenciais.csv", sep = ";", index = False)